name: dflutter_lint_rules
description: Lint rules for "Dizoft Team" company for Dart and Flutter projects.

version: 1.0.1+1

repository: "https://github.com/DizoftTeam/dflutter_lint_rules"
issue_tracker: "https://github.com/DizoftTeam/dflutter_lint_rules/issues"

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.17.0
